# Generated by Django 2.0.3 on 2018-04-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20180331_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeltrain',
            name='collection',
        ),
        migrations.AddField(
            model_name='modeltrain',
            name='collection',
            field=models.ManyToManyField(to='manager.Collection'),
        ),
    ]
