# Generated by Django 2.0.3 on 2018-04-01 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20180401_0731'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionTrainRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='collection',
            name='trains',
        ),
        migrations.AlterField(
            model_name='collection',
            name='trains',
            field=models.ManyToManyField(related_name='collection', through='manager.CollectionTrainRelationship', to='manager.ModelTrain'),
        ),
        migrations.AddField(
            model_name='collectiontrainrelationship',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Collection'),
        ),
        migrations.AddField(
            model_name='collectiontrainrelationship',
            name='trains',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.ModelTrain'),
        ),
    ]
