# Generated by Django 2.0.3 on 2018-04-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20180401_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='trains',
            field=models.ManyToManyField(through='manager.CollectionTrainRelationship', to='manager.ModelTrain'),
        ),
    ]
