# Generated by Django 2.0.3 on 2018-04-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_collection_trains'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectiontrainrelationship',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='collectiontrainrelationship',
            name='trains',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='trains',
        ),
        migrations.AddField(
            model_name='collection',
            name='trains',
            field=models.ManyToManyField(related_name='collection', to='manager.ModelTrain'),
        ),
        migrations.DeleteModel(
            name='CollectionTrainRelationship',
        ),
    ]
