# Generated by Django 2.0.3 on 2018-04-01 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20180401_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='trains',
            field=models.ManyToManyField(through='manager.CollectionTrain', to='manager.ModelTrain'),
        ),
        migrations.AlterField(
            model_name='collectiontrain',
            name='trains',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.ModelTrain'),
        ),
    ]
