# Generated by Django 2.0.3 on 2018-04-01 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20180401_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectiontrain',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.Collection'),
        ),
        migrations.AlterField(
            model_name='collectiontrain',
            name='trains',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.ModelTrain'),
        ),
    ]
