# Generated by Django 2.0.3 on 2018-04-01 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20180401_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectiontrain',
            name='collection',
        ),
        migrations.AddField(
            model_name='collectiontrain',
            name='collection',
            field=models.ForeignKey(null=True, related_name='collectiontrain', on_delete=django.db.models.deletion.CASCADE, to='manager.Collection'),
        ),
    ]
