# Generated by Django 2.0.3 on 2018-04-01 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_auto_20180401_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectiontrain',
            name='collection',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='manager.Collection'),
        ),
    ]
